# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # in ansible.cfg doe je verwijzing naar key..
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.network "private_network", ip: "172.16.0.10"
    web.vm.hostname = "web01"
    web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  end
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "172.16.0.20"
    db.vm.hostname = "db01"
  end
end
