# -*- mode: ruby -*-
# vi: set ft=ruby :
# insert machines like this:
#
# machines = [{:hostname => "bram-env1-test-web",:ip => "172.16.0.111"},
#		{:hostname => "bram-env1-test-db",:ip => "172.16.0.112"}]
machines = [{:hostname => "jantje-pikk-13-web", :ip => "172.16.13.111"},{:hostname => "jantje-pikk-13-db", :ip => "172.16.13.112"}]


Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/home/vagrant/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]

machines.each do |machine|
	config.vm.define machine[:hostname] do |node|
		node.vm.box = "ubuntu/bionic64"
		node.vm.network "private_network", ip: machine[:ip]
		node.vm.hostname = machine[:hostname]
		node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		end
	end
end
