---
- hosts: web 
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=present
    
    - name: install libapache2
      apt: name=libapache2-mod-php state=present

    - name: install php-mysqli
      apt: name=php-mysqli state=present

    - name: copy Hi World script
      copy: src=index.php dest=/var/www/html/index.php mode=0664

    - name: restart apache2
      service: name=apache2 state=restarted 
